<?php

//function wxjs_page_attachments(array &$page) {
////  if (!\Drupal::currentUser()->hasPermission('access contextual links')) {
////    return;
////  }
//  $page['#attached']['library'][] = 'wxjs/wx_js';
//}
use Drupal\node\Entity\Node;
use Drupal\profile\Entity\Profile;
use Drupal\user\Entity\User;

/**
 * Implements hook_preprocess_page().
 */
function wxjs_preprocess_page(&$variables)
{

//  use Drupal\node\Entity\Node;
    // for($i=1026;$i<=1072;$i++){
    //   $nid = $i;
    //   $bid = 1024;
    //   /* @var $node Node */
    //   $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);;//Node::load($nid);
    //   if($i==1066) dpm($node->id());
    //   if($node && $node->id()){
    //     if(!$node->isPromoted()){
    //       continue;
    //     }else{
    //       $node->setPromoted(false);
    //       $node->book=array('bid'=>$bid,'pid'=>$bid);
    //       $node->save();
    //       dpm($node->id() . ' update!');
    //       break;
    //     }
    //   }
    // }


//  ksm($variables);
//  $path = \Drupal::request()->getpathInfo();// /lymeta/im/20161207
    $path = \Drupal::service('path.current')->getPath();// node/1
    $arg = explode('/', $path);
    if ($arg[1] == 'admin') return 0;
    if (in_array('edit', $arg)) return 0;

    $variables['#attached']['library'][] = 'wxjs/wx_js';
    $uid = 4;//
    $config = \Drupal::config('wechat_api.settings')->get('mpaccount_' . $uid);
    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());

    if (is_array($title)) $title = $title['#markup'];
    $shareData = array(
        'title'  => $title . '|主内公众云-永不止息',
        'desc'   => '主内公众云-永不止息,需要有你!欢迎搜索关注公众号:永不止息',//\Drupal::config('system.site')->get('slogan')
        'link'   => "$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
        'imgUrl' => 'https://wx.yongbuzhixi.com/sites/all/themes/jstheme/logo.png',//theme_get_setting('logo.url')
    );
    if ($arg[1] == 'node' && isset($arg[2]) && is_numeric($arg[2])) {
        $cached_data_keyword = 'wxjs_sharedata_node_' . $arg[2];
        if ($cache = \Drupal::cache()->get($cached_data_keyword)) {
            $shareData = $cache->data;
        } else {
            $role_id = 'wechat_account';
            /* @var $node Node */
            $node = $variables['node'];
            /* @var $account User */
            $account = $node->getOwner();
            if ($account->hasRole($role_id)) {
                $profile_type = 'wechat_account_data';
                /* @var $profile Profile */
                $profile = \Drupal::entityTypeManager()->getStorage('profile')
                    ->loadByUser($account, $profile_type);
                $headimgurl = $profile->get('field_mp_accounts_hd_head_img')->value;
                $shareData['imgUrl'] = $headimgurl;
            }
            $body = $node->body->getValue();
            $shareData['desc'] = $body[0]['summary'] ?: $shareData['desc'];

            \Drupal::cache()->set($cached_data_keyword, $shareData, -1);
        }
    }
    $variables['#attached']['drupalSettings']['wxjs']['shareData'] = $shareData;

    require_once "jssdk.php";
    $appid = $config['appid'];
    $appsecret = $config['appsecret'];
    $jssdk = new JSSDK($appid, $appsecret);
    $signPackage = $jssdk->GetSignPackage();
    $variables['#attached']['drupalSettings']['wxjs']['signPackage'] = $signPackage;
}

///**
// * @see hook_node_view().
// */
//function wxjs_node_view($node, $view_mode, $langcode) {
//  if($view_mode=='full'){
//    //2图没有用1图，1图没有用用户图 最后2图默认值！
//    $picurl = '';
//    // dvm(strpos($node->field_image2['und'][0]['uri'],'default_images'));
//    if(isset($node->field_image2['und'][0])&&strpos($node->field_image2['und'][0]['uri'],'default_images')==FALSE){
//      $picurl = file_create_url($node->field_image2['und'][0]['uri']);
//    }
//    if(isset($node->field_image['und'])&&$node->field_image['und'][0]&&strpos($node->field_image['und'][0]['uri'],'default_images')==FALSE){
//      $picurl = file_create_url($node->field_image['und'][0]['uri']);
//    }elseif(variable_get('user_pictures', 0)){
//      if ($node->picture){
//        $imgpath = file_load($node->picture)->uri;
//        $picurl = file_create_url($imgpath);
//      }
//    }
//    if(!$picurl){
//      $info = field_info_instance('node', 'field_image2', 'article');
//      if (!empty($info) && $info['settings']['default_image'] > 0){
//        $default_img_fid  = $info['settings']['default_image'];
//        $default_img_file = file_load($default_img_fid);
//      }
//      $picurl = file_create_url($default_img_file->uri);
//    }
//    // $picurl = theme_get_setting('logo')
//    $desc = variable_get('site_slogan', '主内公众云提供技术支持');
//    if(isset($node->body[LANGUAGE_NONE])){
//      $desc = truncate_utf8(strip_tags($node->body[LANGUAGE_NONE]['0']['value']), 54,  FALSE, TRUE, 1);
//      if($node->body[LANGUAGE_NONE]['0']['summary'])
//         $desc = truncate_utf8(strip_tags($node->body[LANGUAGE_NONE]['0']['summary']), 54,  FALSE, TRUE, 1);
//    }
//    $shareData = array(
//      'title'=> $node->title.'|'.variable_get('site_name', '永不止息'),
//      'desc'=> $desc,
//      'link'=> "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
//      'imgUrl'=> $picurl,
//    );
//    drupal_add_js(array('wxjs' => array('shareData'=>$shareData)), 'setting');
//  }
//}
