<?php
use Drupal\wechat_api\Plugin\Wechat\Wechat;

/**
 * Created by PhpStorm.
 * User: dale.guo
 * Date: 12/22/16
 * Time: 5:43 PM
 */

/**
 * hook_rescources_info
 */
function resource_bbn_rescources_info(){
	$rescources[] = array(
		'name' => 'bbn',
		'desc' => '圣经广播网【400】',
	);
	return $rescources;
}

/**
 * @param $keyword
 * @param Wechat|NULL $weObj
 * @return array
 */
function resource_bbn_wxresources_alter($keyword,Wechat $weObj=NULL){
	$appname = '公众号:永不止息';
	if($weObj){
		$wechat_config = \Drupal::config('wechat_api.settings')->get('mpaccount_'.$weObj->uid);
		$wechat_resources = $wechat_config['wechat_resources'];
		//IF enable ly_resouce 500
		if(!in_array('bbn',$wechat_resources)) return [];
	}

	//http://audio.yongbuzhixi.com/resources/365/2014/20140109.mp3
	$cdnlink = 'http://wxresources.yongbuzhixi.com';
	$check_word = substr($keyword, 0,3);
	if(is_numeric($keyword) && ($keyword>=400 && $keyword<=435) ) {
		// watchdog('mp_liangyou', '400', array(), WATCHDOG_NOTICE, 'link');
		return mp_bbn_response($keyword,$appname);
	}

}


/**
 * $change_keyword = return key!
 */
function mp_bbn_response($keyword,$appname) {
	$change_keyword = $keyword;
	//TODO::dependcy!!!
	$json = file_get_contents('http://bbn.yongbuzhixi.com/cron/bbn/json/'.date('Ym').'/'. date('Ymd') . '.json');
	$json = json_decode($json);
	require_once('bbn.inc');
	if($keyword == '400'){
		$bbn_audio_menu = '▶圣经广播网节目单
    ----------------------------------------------';
		foreach ($json as $key => $value) {
			$bbn_audio_menu = $bbn_audio_menu ."\n".'【'.$key.'】'.$value->title;
		}
		$resources = array(
			'keyword'      =>  $keyword,
			'type'	=>	'text',
			'cache' =>  REQUEST_TIME-1,
			'obj'		=> array(
				'text'	=> $bbn_audio_menu
			)
		);
		return $resources;
	}
	if(isset($json->$keyword->upyun)){
		// $bbn = mp_get_bbn($keyword);
		$objectKey = $json->$keyword->upyun;
		$cdn = 'http://bbn2016.yongbuzhixi.com';
		$musicurl = $cdn . $objectKey;
		// $title = $bbn[$keyword]['title'];
		$title = '【'.$keyword.'】'.$json->$keyword->title;
		$desc = '点击►收听 '.$appname.' 每日更新';//公众号:'.variable_get('mp_config_appname_'.$uid, "永不止息").'
		$resources= array(
			'type'	=>	'music',
			'cache' =>  REQUEST_TIME+43200,
			'upyun_path' => $objectKey,
			'ga_data'   =>  array(
				'category'        => 'bbn',
				'action'          => $title,
			),
			'obj'		=> array(
				'title'	=> $title,
				'desc'	=>	$desc,
				'musicurl'	=>	$musicurl,
				'hgmusicurl'	=>	$musicurl,
			),
		);
		// if(date('G')<11) {
		// 	$resources['key_'.$change_keyword]['custommessage'] = "弟兄姊妹，平安，圣经广播网4开头节目于每早11点更新，请11点后点击播放即可，谢谢代祷推荐给亲朋好友\n永不止息，需要有你[握手]";
		//  }
	}else{
		$text = "【$keyword 】今日无节目或节目还没有加速，小永努力中，请稍后再试！\n永不止息，需要有你[握手]\n请回复【400】收听其他节目，";
		$resources = array(
			'keyword'      =>  $keyword,
			'type'	=>	'text',
			'ga_data'   =>  array(
				'category'        => 'bbn',
				'action'          => "no $keyword yet!",
			),
			'cache' =>  REQUEST_TIME-1,
			'obj'		=> array(
				'text'	=> $text
			)
		);
	}
	return $resources;
}
