<?php
/**
 * Created by PhpStorm.
 * User: dale.guo
 * Date: 11/25/16
 * Time: 4:10 PM
 */
use Drupal\user\Entity\User;
use Drupal\profile\Entity\Profile;

// [
// 	'field_fytv_video_id'=>45053,
// 	'status'=>1,
// 	'created'=>'190099202',
// 	'field_tags.entity.name'=>'cats',
// 	'field_lymeta_tid.entity.tid'=>$tid
// ]
function wxapi_get_nid($fields,$bundle='grace'){
    $bundle = 'grace';
    // $created = strtotime($date . ' 08:00:00 AM');
    $query = \Drupal::entityQuery('node');
    $query->condition('type', $bundle);
    foreach($fields as $key => $value) {
    	$query->condition($key, $value);
    }
    $query->range(0, 1);
//  https://www.sitepoint.com/drupal-8-version-entityfieldquery/
//	https://lakshminp.com/using-entity-api-drupal-8
//  ->condition('field_tags.entity.name', 'cats');
    $entity_ids = $query->execute();
    if (count($entity_ids)) {
        return $entity_ids[array_keys($entity_ids)[0]];
    } else {
        return NULL;
    }
}

//cron set new user pic url field then delete!!!
function wxapi_cron() {
    // https://api.drupal.org/api/drupal/core!includes!database.inc/function/db_select/8.2.x
    $query = \Drupal::database()->select('user__field_user_picture_url', 't');
    $query->addField('t', 'entity_id');
    $query->condition('t.bundle', 'user');
    $subquery_result = array_keys($query->execute()->fetchAllAssoc('entity_id'));
    if(empty($subquery_result)) $subquery_result=[0];
    $query = \Drupal::database()->select('user__field_user_openids', 't');
    $query->addField('t', 'entity_id');
    $query->condition('t.bundle', 'user');
    $query->condition('t.entity_id', $subquery_result, 'NOT IN');
    $query->range(0, 100);
    $uids = array_keys($query->execute()->fetchAllAssoc('entity_id'));
    foreach ($uids as $uid) {
        $user = User::load($uid);
        $profile_type = 'wechat_user_data';
        /* @var $profile Profile */
        $profile = \Drupal::entityTypeManager()->getStorage('profile')
            ->loadByUser($user, $profile_type);
        if ($profile && $profile->get('field_wxuser_headimgurl')->value!=$user->get('field_user_picture_url')->value) {
            // \Drupal::logger('wxapi_cron')->notice($uid);
            $user->set('field_user_picture_url', $profile->get('field_wxuser_headimgurl')->value);
            $user->save();
        }
    }
    // return $uids; 
}