<?php
/**
 * Created by PhpStorm.
 * User: dale.guo
 * Date: 11/25/16
 * Time: 4:10 PM
 */

// [
// 	'field_fytv_video_id'=>45053,
// 	'status'=>1,
// 	'created'=>'190099202',
// 	'field_tags.entity.name'=>'cats',
// 	'field_lymeta_tid.entity.tid'=>$tid
// ]
function wxapi_get_nid($fields,$bundle='grace'){
    $bundle = 'grace';
    // $created = strtotime($date . ' 08:00:00 AM');
    $query = \Drupal::entityQuery('node');
    $query->condition('type', $bundle);
    foreach($fields as $key => $value) {
    	$query->condition($key, $value);
    }
    $query->range(0, 1);
//  https://www.sitepoint.com/drupal-8-version-entityfieldquery/
//	https://lakshminp.com/using-entity-api-drupal-8
//  ->condition('field_tags.entity.name', 'cats');
    $entity_ids = $query->execute();
    if (count($entity_ids)) {
        return $entity_ids[array_keys($entity_ids)[0]];
    } else {
        return NULL;
    }
}
