<?php
/**
 * @param $keyword
 * @param Wechat|NULL $weObj
 * @return array
 */
use Drupal\Component\Utility\Unicode;
use Drupal\wechat_api\Plugin\Wechat\Wechat;
use Drupal\node\NodeInterface;

/**
 * hook_rescources_info
 */
function resource_77_rescources_info(){
    $rescources[] = array(
        'name' => '77',
        'desc' => '自建音频资源【770】',
    );
    $rescources[] = array(
        'name' => '77_share',
        'desc' => '接入共享自建音频资源【770】',
    );
    return $rescources;
}

function resource_77_wxresources_alter($keyword, Wechat $weObj = NULL) {
    if (!$weObj) return [];
    $wechat_config = \Drupal::config('wechat_api.settings')->get('mpaccount_' . $weObj->uid);
    $wechat_resources = $wechat_config['wechat_resources'];
    $appname = "公众号:" . $wechat_config['appname'];
    //IF enable 77
    if (!in_array('77', $wechat_resources)) return [];

    $check_word = substr($keyword, 0, 2);
    $index = (int)substr($keyword, 2);
    if ($keyword == 770) {
        $list_count = 15;
        //1.get all fm77 nids&&titles of this account!!!or shared!!!
        $fields = [
         'status'=>NodeInterface::PUBLISHED,  //1
         'field_tags.entity.name'=>'FM77',
         // 'field_lymeta_tid.entity.tid'=>$tid
        ];
        if (in_array('77_share', $wechat_resources)){
            $uid = $weObj->uid;
            $uid = 43462;
            $nids = tools_wxapi_get_nids($fields,'article',15,$uid);
            $total = count(tools_wxapi_get_nids($fields,'article',-1,$uid));
        }else{
            $nids = tools_wxapi_get_nids($fields,'article',15);
            $total = count(tools_wxapi_get_nids($fields,'article',-1));
        }
        $titles = tools_get_titles($nids);
        $menu = '';
        foreach ($nids as $key => $nid) {
           $menu .= '【' . $total-$list_count+$key . '】' . $titles[$key] . "\n";
        }
        $resources = [
            'keyword' => $keyword,
            'type'    => 'text',
            'expire'  => -1,//-1 never expires.
            'obj'     => [
                'text' => $menu,
            ],
            'ga_data' => array(
                'category' => 'menu get',
                'action'   => '77',
            ),
        ];
        return $resources;
    }

    if ($check_word == 77 && !$index) {

    }
    // 
}