<?php
use Drupal\Component\Utility\Unicode;
use Drupal\node\Entity\Node;


// [
// 	'field_fytv_video_id'=>45053,
// 	'status'=>1,
//  'promote'=>1
//  'sticky'=>1
// 	'created'=>'190099202',
// 	'field_tags.entity.name'=>'cats',
// 	'field_lymeta_tid.entity.tid'=>$tid
// ]
function tools_wxapi_get_nid($fields,$bundle='grace',$count=1,$uid=0){
	$nids = tools_wxapi_get_nids($fields,$bundle='grace',$count=1,$uid=0);
	if($nids) $nids[0];
	return NULL;
}
function tools_wxapi_get_nids($fields,$bundle='grace',$count=1,$uid=0){
    // $created = strtotime($date . ' 08:00:00 AM');
    $query = \Drupal::entityQuery('node');
    $query->condition('type', $bundle);
    if($uid) $query->condition('uid', $uid);
    foreach($fields as $key => $value) {
    	$query->condition($key, $value);
    }
    $query->range(0, $count);

//  https://www.sitepoint.com/drupal-8-version-entityfieldquery/
//	https://lakshminp.com/using-entity-api-drupal-8
//  ->condition('field_tags.entity.name', 'cats');
    $entity_ids = $query->execute();
    if (count($entity_ids)) {
      return array_values($entity_ids);
    } else {
        return NULL;
    }
}

function tools_wechat_api_get_news($nids){
    $news=[];
    foreach ($nids as $key => $nid) {
        $node = Node::load($nid);
        $desc = $node->body->summary?:Unicode::truncate($node->body->value, '54', TRUE, TRUE);
        if(!$desc) $desc="只有音频/视频";
        $url = Url::fromRoute('entity.node.canonical', ['node' => $nid],['absolute' => TRUE])->toString();
        if(!$node->field_image_url->isEmpty()) $picurl = $node->field_image_url->value;
        if(!$node->field_image->isEmpty()) {
            $fid = $node->field_image->getValue()[0]['target_id'];
            // https://drupal.stackexchange.com/questions/200741/generate-image-url-from-fid
            $file = \Drupal\file\Entity\File::load($fid);
            $picurl = file_create_url($file->getFileUri());
        }
        if(!$picurl)  $picurl = 'http://mmbiz.qpic.cn/mmbiz_jpg/I2rbxqsBRK3W4pJUhm0Cj304u9fUsxPtkPZaiaZ23J5WDzcNfbQE0Szy3UMJzOz5coloCdh2JWN58BOic3E94cMw/0?wx_fmt=jpeg';
        $img = array(
          'Title'=> $node->getTitle(),
          'Description'=>$desc,
          'PicUrl'=> $picurl,//field_image_url($node->field_image['und'][0]['uri']),
          'Url'=> $url,
        );
        $news[] = $img;
    }
    return $news;
}